apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-app
  labels:
    app: stress-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stress-app
  template:
    metadata:
      name: stress-app
      labels:
        app: stress-app
    spec:
      containers:
        - name: stress-app
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: stress-app-service
spec:
  selector:
    app: stress-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
