apiVersion: v1
kind: ConfigMap
metadata:
  name: stress-js-cm
data:
  test.js: |
    import http from "k6/http";
    const BASE_URL = "http://stress-app-service:8080";
    export let options = {
        vus: 5,
        duration: '10s'
    };
    export default function(){
        http.get(`${BASE_URL}/`);
    }

---


apiVersion: batch/v1
kind: Job
metadata:
  name: stress-job
spec:
  template:
    spec:
      containers:
        - name: k6
          image: grafana/k6:latest
          command: ["k6", "run", "/scripts/test.js"]
          volumeMounts:
            - name: stress-cm
              mountPath: "/scripts/test.js"
              subPath: test.js
              readOnly: true
      volumes:
        - name: stress-cm
          configMap:
            name: stress-js-cm
      restartPolicy: Never
  backoffLimit: 4


