apiVersion: v1
kind: ConfigMap
metadata:
  name: myenglish-db-cf
  namespace: {{.Release.Namespace}}
data:
  # プロパティーに似たキー。各キーは単純な値にマッピングされている
  #  MYSQL_DATABASE
  mysql_database: "{{ .Values.config.db.mysql_database }}"
  # MYSQL_USER
  mysql_user: "{{ .Values.config.db.mysql_user }}"
  # MYSQL_PASSWORD
  mysql_password: "{{ .Values.config.db.mysql_password }}"
  # MYSQL_ROOT_PASSWORD
  mysql_root_password: "{{ .Values.config.db.mysql_root_password }}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myenglish-db-deployment
  namespace: {{.Release.Namespace}}
  labels:
    app: myenglish-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myenglish-db
  template:
    metadata:
      labels:
        app: myenglish-db
    spec:
      containers:
        - name: myenglish-db
          image: mysql
          ports:
            - containerPort: 3306
          env:
            # 環境変数を定義します。
            - name: MYSQL_DATABASE # ここではConfigMap内のキーの名前とは違い大文字
              # 大文字が使われていることに着目してください。
              valueFrom:
                configMapKeyRef:
                  name: myenglish-db-cf           # この値を取得するConfigMap。
                  key: mysql_database # 取得するキー。
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: myenglish-db-cf
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: myenglish-db-cf
                  key: mysql_password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: myenglish-db-cf
                  key: mysql_root_password
---

apiVersion: v1
kind: Service
metadata:
  name: myenglish-db-service
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: myenglish-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306