apiVersion: apps/v1
kind: Deployment
metadata:
  name: myenglish-front-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: myenglish-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myenglish-front
  template:
    metadata:
      labels:
        app: myenglish-front
    spec:
      containers:
        - name: myenglish-front
          image: "{{ .Values.image.registry }}/{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.version }}"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: myenglish-front-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: myenglish-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

